### ISSUE TITLE
Is it simply compiled library of webrtc source code of Google?

### ISSUE THREAD

**Issue by AdilSoomro** [Namdole/GoogleWebRTC#2]
I was wondering, if you've made any changes to source while compiling or is it a simple compiled library of Google's webrtc source code?

The library on cocoapod is old and crashes on iOS 13.

So is it okay to use your compiled library my project?

**Comment by AdilSoomro** [comment]
Nevermind, I realized I could use the Google's nightly build until they release an official one. [iOS API Framework Builder](https://ci.chromium.org/p/webrtc/builders/ci/iOS%20API%20Framework%20Builder)

**Comment by Namdole** [comment]
You can use my complied library for your project, configure disable bitcode.
